<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_plants.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['rubrik'][0]         = 'Rubrik';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['rubrik'][1]         = 'Rubrik der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['name_de'][0]		= 'deutscher Name';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['name_de'][1]        = 'deutscher Name für die Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['name_bot'][0]		= 'botanischer Name';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['name_bot'][1]       = 'botanischer Name für die Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['licht'][0]			= 'Licht';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['licht'][1]          = 'Lichteigenschaft der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['boden'][0]			= 'Boden';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['boden'][1]          = 'Bodeneigenschaften der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['feuchte'][0]		= 'Feuchte';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['feuchte'][1]        = 'Feuchteeigenschaften der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['hoehe'][0]		= 'Höhe';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['hoehe_ab'][0]		= 'Höhe (ab)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['hoehe_ab'][1]       = 'Höhe der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['hoehe_bis'][0]		= 'Höhe (bis)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['hoehe_bis'][1]       = 'max Höhe der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluezeit'][0]	= 'Blühzeit';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluezeit_ab'][0]	= 'Blühzeit (ab)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluezeit_ab'][1]    = 'im zweistelligen Monatszahl wie 02 für Februar';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluezeit_bis'][0]	= 'Blühzeit (bis)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluezeit_bis'][1]   = 'im zweistelligen Monatszahl wie 02 für Februar';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['nektar'][0]			= 'Nektar';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['nektar'][1]			= 'Nektarwert der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['pollen'][0]			= 'Pollen';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['pollen'][1]			= 'Pollenwert der Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluetenfarbe'][0]			= 'Blütenfarbe';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['bluetenfarbe'][1]			= 'Farbe der Blüten';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['wikipedia_link'][0]			= 'URL (Wikipedia)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['wikipedia_link'][1]			= 'Die URL zum Wikipedia-Eintrag dieser Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['image_wikimedia'][0]			= 'Bild (extern)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['image_wikimedia'][1]			= 'Die URL zur externen Bildquelle dieser Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['image_local'][0]			= 'Bild (intern)';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['image_local'][1]			= 'Die URL zur externen Bildquelle dieser Pflanze';

/**
* Legends
*/
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['property_legend']       = 'Eigenschaften';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['new'][0]                          = 'Neue Pflanze';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['new'][1]                          = 'Eine neue Pflanze anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['edit'][0]                         = 'Pflanze bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['edit'][1]                         = 'Pflanze ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['copy'][0]                         = 'Pflanze duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['copy'][1]                         = 'Pflanze ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['delete'][0]                       = 'Pflanze löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['delete'][1]                       = 'Pflanze ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['show'][0]                         = 'Pflanzendetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_plants']['show'][1]                         = 'Details für Pflanze ID %s anzeigen.';

