<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_pollen.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['text'][0]         = 'Begriff';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['text'][1]         = 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['new'][0]                          = 'Neue Pollenbewertung';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['new'][1]                          = 'Eine neue Pollenbewertung anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['edit'][0]                         = 'Pollenbewertung bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['edit'][1]                         = 'Pollenbewertung ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['copy'][0]                         = 'Pollenbewertung duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['copy'][1]                         = 'Pollenbewertung ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['delete'][0]                       = 'Pollenbewertung löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['delete'][1]                       = 'Pollenbewertung ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['show'][0]                         = 'Pollenbewertungdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_pollen']['show'][1]                         = 'Details für Pollenbewertung ID %s anzeigen.';

