<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_light.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_light']['text'][0]         = 'Begriff';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['text'][1]         = 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_light']['new'][0]                          = 'Neues Lichtverhältnis';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['new'][1]                          = 'Ein neues Lichtverhältnis anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['edit'][0]                         = 'Lichtverhältnis bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['edit'][1]                         = 'Lichtverhältnis ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['copy'][0]                         = 'Lichtverhältnis duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['copy'][1]                         = 'Lichtverhältnis ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['delete'][0]                       = 'Lichtverhältnis löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['delete'][1]                       = 'Lichtverhältnis ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['show'][0]                         = 'Lichtverhältnisdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_light']['show'][1]                         = 'Details für Lichtverhältnis ID %s anzeigen.';

