<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_ground.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['text'][0]         	= 'Begriff';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['text'][1]         	= 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['new'][0]                          = 'Neuer Boden';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['new'][1]                          = 'Ein neuen Boden anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['edit'][0]                         = 'Boden bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['edit'][1]                         = 'Boden ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['copy'][0]                         = 'Boden duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['copy'][1]                         = 'Boden ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['delete'][0]                       = 'Boden löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['delete'][1]                       = 'Boden ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['show'][0]                         = 'Bodendetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_ground']['show'][1]                         = 'Details für Boden ID %s anzeigen.';

