<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_nectar.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['text'][0]         = 'Begriff';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['text'][1]         = 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['new'][0]                          = 'Neue Nektarbewertung';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['new'][1]                          = 'Eine neue Nektarbewertung anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['edit'][0]                         = 'Nektarbewertung bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['edit'][1]                         = 'Nektarbewertung ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['copy'][0]                         = 'Nektarbewertung duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['copy'][1]                         = 'Nektarbewertung ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['delete'][0]                       = 'Nektarbewertung löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['delete'][1]                       = 'Nektarbewertung ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['show'][0]                         = 'Nektarbewertungdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_nectar']['show'][1]                         = 'Details für Nektarbewertung ID %s anzeigen.';

