<?php
/**
 * TL_ROOT/system/modules/beekeeping_bee_pasture/languages/de/tl_bk_bp_categories.php
 *
 * Contao extension: beekeeping_bee_pasture
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['rubrik'][0]         = 'Titel';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['rubrik'][1]         = 'Titel der Rubrik';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['alias'][0]			= 'Alias';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['alias'][1]        	= 'wird z.B. für die URL-Übergabe benötigt';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['new'][0]                          = 'Neue Rubrik';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['new'][1]                          = 'Eine neue Rubrik anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['edit'][0]                         = 'Rubrik bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['edit'][1]                         = 'Rubrik ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['copy'][0]                         = 'Rubrik duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['copy'][1]                         = 'Rubrik ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['delete'][0]                       = 'Rubrik löschen';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['delete'][1]                       = 'Rubrik ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['show'][0]                         = 'Rubrikdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bp_categories']['show'][1]                         = 'Details für Rubrik ID %s anzeigen.';

